.TH filter-log 1
.SH NAME
filter-log \- format JSON based logs to be human-readable
.SH SYNOPSIS
cat my-log.json |
.B filter-log
[\fB\-f\fR \fI'js-code'\fR]
[\fB\-\-tri\fR=\fI\'tripartite-template\'\fR]

.SH DESCRIPTION
.B filter-log
Filter Log helps create, save, and format log information. The command
line tool will format JSON based logs into more human-readable lines. To use filter-log,
pipe the log JSON into the command. The date of the log entry and the message from
the log entry will show up on a single line.
.SH OPTIONS
.TP
.BR \-f \fIjavascript-expression\fR
A javascript expression to format the log entry. Every member of the log
entry is available. The default formatting expression if no formatting mechanism
is specified is: date + " \- " + msg
.TP
.BR \-\-tri =\fItripartite-template\fR
A tripartite template to format the log entry. Every member of the log
entry is available. An example which matches the default formatting would be: 
__date__ - __msg__